"use strict";

const DETERMINATION_TEMPLATE = Object.freeze({
  TEMPLATE_1: "DETERMINATION: ELIGIBLE FOR DESKTOP AND MOBILE TECHNICAL RECORD BUILD",
  TEMPLATE_2: "DETERMINATION: ELIGIBLE FOR DESKTOP TECHNICAL RECORD BUILD",
  TEMPLATE_3: "DETERMINATION: ELIGIBLE FOR DESKTOP TECHNICAL RECORD BUILD / MOBILE BASELINE: CONSTRAINED",
  TEMPLATE_4: "DETERMINATION: ELIGIBLE FOR MOBILE TECHNICAL RECORD BUILD",
  TEMPLATE_5: "DETERMINATION: ELIGIBLE FOR MOBILE TECHNICAL RECORD BUILD / DESKTOP BASELINE: CONSTRAINED",
  TEMPLATE_6: "DETERMINATION: NOT ELIGIBLE FOR FORENSIC EXECUTION",
  TEMPLATE_7: "DETERMINATION: NOT ELIGIBLE FOR FORENSIC EXECUTION - CONSTRAINTS (BOTMITIGATION)",
  TEMPLATE_8: "DETERMINATION: NOT ELIGIBLE FOR FORENSIC EXECUTION - CONSTRAINTS (OTHER)",
});

const TEMPLATE_VALUES = Object.freeze(Object.values(DETERMINATION_TEMPLATE));
const NOTE_ALLOWED_TEMPLATES = Object.freeze(
  new Set([
    DETERMINATION_TEMPLATE.TEMPLATE_3,
    DETERMINATION_TEMPLATE.TEMPLATE_5,
  ])
);

module.exports = Object.freeze({
  DETERMINATION_TEMPLATE,
  TEMPLATE_VALUES,
  NOTE_ALLOWED_TEMPLATES,
});